export enum PlayerPassiveType {
  POISONOUS_MUSHROOM,
  MOLDY_CHEESE,
  MASK,
  POCKET_WATCH,
  CLOWN_NOSE,
  SUSPICIOUS_MIXTURE,
  TEDDY_BEAR,
  FEATHER,
  UNICORN_HORN,
  CLOVER,
  CANDY_CANE,
  ENERGIZED_DRINK,
}
